### PR TITLE
remove chromedriver; update to java 11

### PR DESCRIPTION
**Pull request by donna-marijne**
- remove chromedriver.
- update to Java 11.

### CODE REVIEW

**Comment by donna-marijne** [comment]
Downstream build to verify:
https://github.houston.softwaregrp.net/Inner-Source-Incubating/ux-aspects-universal/pull/1193
https://jenkins.swinfra.net/job/SEPG/job/Inner-Source-Incubating/job/Inner-Source-Incubating~ux-aspects-universal~issue-1173-node-16~CI/

**Comment by ashley-hunter** [comment]
Thanks Donna, looks good. Just checking, will UX Aspects ever need to use this image? As those E2E tests still rely on Protractor?

**Comment by donna-marijne** [comment]
No, UX Aspects is still using the original build image here:
https://github.com/UXAspects/buildenv-image

I updated that to Node 16 earlier this year.

**Review by ashley-hunter — APPROVED** [review]
Thanks for clarifying, all good then!

**Pull request merged**
